SELECT * from AMENITY;

INSERT INTO AMENITY
    VALUES (001, SYSDATE, SYSDATE, '01 amenity');
    
INSERT INTO AMENITY
    VALUES (002, SYSDATE, SYSDATE, '02 amenity');
    
INSERT INTO AMENITY
    VALUES (003, SYSDATE, SYSDATE, '04 amenity');    

INSERT INTO AMENITY
    VALUES (004, SYSDATE, SYSDATE, '03 amenity');
    
INSERT INTO AMENITY
    VALUES (005, SYSDATE, SYSDATE, '05 amenity');