SELECT * from REVIEW;

INSERT INTO REVIEW
    VALUES (001, SYSDATE, SYSDATE, 1, 1, 'String 1');
    
INSERT INTO REVIEW
    VALUES (002, SYSDATE, SYSDATE, 2, 2, 'String 2');
    
INSERT INTO REVIEW
    VALUES (003, SYSDATE, SYSDATE, 3, 3, 'String 3');
    
INSERT INTO REVIEW
    VALUES (004, SYSDATE, SYSDATE, 4, 4, 'String 4');
    
INSERT INTO REVIEW
    VALUES (005, SYSDATE, SYSDATE, 5, 5, 'String 5');