SELECT * from PLACE_AMENITY;

INSERT INTO PLACE_AMENITY
    VALUES (001, 1);
    
INSERT INTO PLACE_AMENITY
    VALUES (002, 2);
    
INSERT INTO PLACE_AMENITY
    VALUES (003, 3);
    
INSERT INTO PLACE_AMENITY
    VALUES (004, 4);
    
INSERT INTO PLACE_AMENITY
    VALUES (005, 5);